name=input("Enter your name:")
age=int(input("Enter your age:"))
height=float(input("Enter your height:"))
gender=input("Enter your gender: ")
print("\n Student details")
print("name:",name)
print("age:",age)
print("height:",height,"cm")
print("gender:",gender)
