num1=float(input("Enter first number: "))
num2=float(input("Enter second number: "))
num3=float(input("Enter third number: "))
num4=float(input("Enter fourth number: "))
maximum=max(num1,num2,num3,num4)
print("The maximum number is",maximum)